export const FETCH_AUTH_PLAYER = 'FETCH_AUTH_PLAYER';
export const RECEIVE_AUTH_PLAYER = 'RECEIVE_AUTH_PLAYER';
export const FAIL_AUTH_PLAYER = 'FAIL_AUTH_PLAYER';

export const FETCH_AUTH_LEADING = 'FETCH_AUTH_LEADING';
export const RECEIVE_AUTH_LEADING = 'RECEIVE_AUTH_LEADING';
export const FAIL_AUTH_LEADING = 'FAIL_AUTH_LEADING';

export const FETCH_SIGN_OUT = 'FETCH_SIGN_OUT';
export const RECEIVE_SIGN_OUT = 'RECEIVE_SIGN_OUT';
export const FAIL_SIGN_OUT = 'FAIL_SIGN_OUT';

export const PUSH_THE_BUTTON = 'PUSH_THE_BUTTON';

export const RESET_PLAYER_LIST = 'RESET_PLAYER_LIST';

export const RESET_ALL = 'RESET_ALL';